### ISSUE TITLE
cannot find module 'highligh.js'

### ISSUE THREAD

**Issue by Alex-Lin** [yoshuawuyts/vmd#93]
how to fix this problem:

**A JavaScript error occurred in the main process**

Uncaught Exception:
Error: Cannot find module 'highlight.js'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/linli/.nvm/versions/node/v4.7.0/lib/node_modules/vmd/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.resolve (internal/module.js:27:19)
    at Object.exports.getHighlightTheme (/Users/linli/.nvm/versions/node/v4.7.0/lib/node_modules/vmd/main/styles.js:24:40)
    at Function.<anonymous> (/Users/linli/.nvm/versions/node/v4.7.0/lib/node_modules/vmd/main/create-window.js:174:20)

**Comment by Alex-Lin** [comment]
This issue is caused by **nvm**.

Installing node 6 lts by pkg resolved my problem.
